on:
  push:

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install gcc
      - run: ./build.sh
      - run: ./test.sh

name: Run tests
